// Package doctemplate generates safety documentation templates for
// multi-language projects in Markdown format.
//
// Generate selects templates from the standard library by the requested
// safety standards (ISO 26262, DO-178C, IEC 61508, ISO 21434) and writes
// them as Markdown files to an output directory. A Report documents what was
// generated, which can be persisted and rendered as text or JSON.
package doctemplate

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"

	fusaops "github.com/SoundMatt/FuSaOps"
)

// ReportFile is the default filename for the persisted template report.
//
//fusa:req REQ-FO-TMPL001
const ReportFile = ".fusaops-templates.json"

// DefaultOutputDir is the default subdirectory for generated template files.
//
//fusa:req REQ-FO-TMPL001
const DefaultOutputDir = "safety-docs"

// DocKind classifies the purpose of a safety document template.
//
//fusa:req REQ-FO-TMPL001
type DocKind string

const (
	DocKindPlan         DocKind = "plan"
	DocKindRequirements DocKind = "requirements"
	DocKindReport       DocKind = "report"
	DocKindChecklist    DocKind = "checklist"
)

// DocTemplate holds the definition of one safety document template.
//
//fusa:req REQ-FO-TMPL001
type DocTemplate struct {
	ID        string   `json:"id"`
	Name      string   `json:"name"`
	Kind      DocKind  `json:"kind"`
	Standards []string `json:"standards"` // empty means "all standards"
	Filename  string   `json:"filename"`
	Content   string   `json:"-"` // not serialised — content is on disk after generation
}

// GeneratedDoc records one template file that was written to disk.
//
//fusa:req REQ-FO-TMPL001
type GeneratedDoc struct {
	TemplateID string `json:"templateId"`
	Name       string `json:"name"`
	Path       string `json:"path"`
	Size       int64  `json:"size"`
}

// Report is the top-level document generation report.
//
//fusa:req REQ-FO-TMPL001
type Report struct {
	GeneratedAt    time.Time      `json:"generatedAt"`
	ProjectRoot    string         `json:"projectRoot"`
	Tool           string         `json:"tool"`
	ToolVersion    string         `json:"toolVersion"`
	OutputDir      string         `json:"outputDir"`
	Standards      []string       `json:"standards"`
	Generated      []GeneratedDoc `json:"generated"`
	TotalGenerated int            `json:"totalGenerated"`
	Hash           string         `json:"hash"`
}

// contentSP001 is the Software Safety Plan template content.
var contentSP001 = "# Software Safety Plan\n\n" +
	"## 1. Purpose and Scope\n\n" +
	"This Software Safety Plan (SSP) defines the development and verification activities\n" +
	"required to achieve the target safety integrity level for this project.\n\n" +
	"- **Project:** <!-- project name -->\n" +
	"- **Standard:** <!-- ISO 26262 / IEC 61508 / DO-178C / ISO 21434 -->\n" +
	"- **Integrity Level:** <!-- ASIL-B / SIL-2 / DAL-C / etc. -->\n" +
	"- **Revision:** 1.0\n" +
	"- **Date:** <!-- YYYY-MM-DD -->\n\n" +
	"## 2. Safety Goals\n\n" +
	"| ID | Safety Goal | Integrity Level |\n" +
	"|----|-------------|------------------|\n" +
	"| SG-001 | <!-- describe safety goal --> | <!-- level --> |\n\n" +
	"## 3. Development Process\n\n" +
	"| Phase | Activity | Output | Responsible |\n" +
	"|-------|----------|--------|-------------|\n" +
	"| Planning | Define safety plan | This document | Safety Engineer |\n" +
	"| Requirements | Elicit safety requirements | SRS | Systems Engineer |\n" +
	"| Design | Architectural design | SDD | Software Architect |\n" +
	"| Implementation | Coding and unit testing | Source + evidence | Developer |\n" +
	"| Verification | Integration and system test | Test reports | Test Engineer |\n" +
	"| Certification | Compile evidence | Audit pack | Safety Engineer |\n\n" +
	"## 4. Tools and Environment\n\n" +
	"| Tool | Version | Qualification Status |\n" +
	"|------|---------|---------------------|\n" +
	"| FuSaOps | <!-- version --> | <!-- qualified / not required --> |\n" +
	"| <!-- language tool --> | <!-- version --> | <!-- status --> |\n\n" +
	"## 5. Traceability\n\n" +
	"Safety requirements shall be traced from safety goals through design to tests.\n" +
	"Run fusaops trace to generate the cross-language traceability matrix.\n\n" +
	"## 6. Problem Reporting\n\n" +
	"All safety-relevant defects shall be recorded using fusaops pr.\n\n" +
	"## 7. Configuration Management\n\n" +
	"The Software Configuration Index is generated by fusaops sci.\n\n" +
	"## 8. Sign-off\n\n" +
	"| Role | Name | Date | Signature |\n" +
	"|------|------|------|----------|\n" +
	"| Safety Manager | | | |\n" +
	"| Project Lead | | | |\n"

var contentSP002 = "# Hazard Analysis and Risk Assessment (HARA)\n\n" +
	"## 1. Document Information\n\n" +
	"- **Project:** <!-- project name -->\n" +
	"- **Standard:** ISO 26262 / IEC 61508\n" +
	"- **Revision:** 1.0\n" +
	"- **Date:** <!-- YYYY-MM-DD -->\n\n" +
	"## 2. Operational Situations\n\n" +
	"| ID | Situation | Description |\n" +
	"|----|-----------|-------------|\n" +
	"| OS-001 | Normal operation | <!-- describe --> |\n" +
	"| OS-002 | Maintenance mode | <!-- describe --> |\n\n" +
	"## 3. Hazard Identification\n\n" +
	"| ID | Hazard | Event | Operational Situation |\n" +
	"|----|--------|-------|------------------------|\n" +
	"| H-001 | <!-- hazard --> | <!-- event --> | <!-- OS-xxx --> |\n\n" +
	"## 4. Risk Assessment\n\n" +
	"| Hazard | Severity | Exposure | Controllability | ASIL | Safety Goal |\n" +
	"|--------|----------|----------|-----------------|------|-------------|\n" +
	"| H-001 | S<!-- 0-3 --> | E<!-- 0-4 --> | C<!-- 0-3 --> | <!-- QM/A-D --> | SG-001 |\n\n" +
	"## 5. Safety Goals\n\n" +
	"| ID | Safety Goal | ASIL | Derived From |\n" +
	"|----|-------------|------|---------------|\n" +
	"| SG-001 | <!-- The system shall... --> | <!-- ASIL --> | H-001 |\n\n" +
	"## 6. Notes\n\n" +
	"<!-- Additional analysis, assumptions, excluded hazards -->\n"

var contentSP003 = "# Software Requirements Specification\n\n" +
	"## 1. Document Information\n\n" +
	"- **Project:** <!-- project name -->\n" +
	"- **Standard:** <!-- standard -->\n" +
	"- **Integrity Level:** <!-- level -->\n" +
	"- **Revision:** 1.0\n" +
	"- **Date:** <!-- YYYY-MM-DD -->\n\n" +
	"## 2. System Context\n\n" +
	"<!-- Describe the system boundary, interfaces, and operating environment -->\n\n" +
	"## 3. Functional Requirements\n\n" +
	"| ID | Requirement | Priority | Verification Method |\n" +
	"|----|-------------|----------|---------------------|\n" +
	"| SRS-001 | <!-- The software shall... --> | MUST | Test |\n\n" +
	"## 4. Safety Requirements\n\n" +
	"| ID | Requirement | Safety Goal | Integrity Level |\n" +
	"|----|-------------|-------------|------------------|\n" +
	"| SR-001 | <!-- The software shall... --> | SG-001 | <!-- level --> |\n\n" +
	"## 5. Non-Functional Requirements\n\n" +
	"| ID | Category | Requirement |\n" +
	"|----|----------|-------------|\n" +
	"| NFR-001 | Timing | <!-- response time constraint --> |\n" +
	"| NFR-002 | Memory | <!-- memory constraint --> |\n\n" +
	"## 6. Interface Requirements\n\n" +
	"| Interface | Type | Description |\n" +
	"|-----------|------|-------------|\n" +
	"| <!-- name --> | <!-- HW/SW/Comm --> | <!-- description --> |\n\n" +
	"## 7. Traceability to Safety Goals\n\n" +
	"| Safety Goal | Derived Requirements |\n" +
	"|-------------|---------------------|\n" +
	"| SG-001 | SR-001, SR-002 |\n"

var contentSP004 = "# Test Plan and Verification Report\n\n" +
	"## 1. Document Information\n\n" +
	"- **Project:** <!-- project name -->\n" +
	"- **Standard:** <!-- standard -->\n" +
	"- **Revision:** 1.0\n" +
	"- **Date:** <!-- YYYY-MM-DD -->\n\n" +
	"## 2. Test Strategy\n\n" +
	"| Level | Method | Coverage Target |\n" +
	"|-------|--------|------------------|\n" +
	"| Unit | Automated (go test / cargo test / pytest) | Statement >= 80% |\n" +
	"| Integration | Automated (fusaops check) | All adapter interfaces |\n" +
	"| System | Manual + automated | All safety requirements |\n\n" +
	"## 3. Test Cases\n\n" +
	"| ID | Requirement | Description | Expected Result | Pass/Fail |\n" +
	"|----|-------------|-------------|-----------------|----------|\n" +
	"| TC-001 | SR-001 | <!-- test description --> | <!-- expected --> | |\n\n" +
	"## 4. Structural Coverage\n\n" +
	"Run fusaops coverage to generate the DO-178C structural coverage report.\n\n" +
	"| Language | Statement | Branch | MC/DC |\n" +
	"|----------|-----------|--------|-------|\n" +
	"| Go | <!-- % --> | <!-- % --> | N/A |\n" +
	"| C | <!-- % --> | <!-- % --> | <!-- % --> |\n\n" +
	"## 5. Regression Summary\n\n" +
	"Generated by fusaops verify. See .fusaops-evidence.json.\n\n" +
	"## 6. Open Test Issues\n\n" +
	"| ID | Description | Severity | Resolution |\n" +
	"|----|-------------|----------|------------|\n" +
	"| | | | |\n\n" +
	"## 7. Sign-off\n\n" +
	"All tests passing as of: <!-- date -->\n\n" +
	"| Role | Name | Date |\n" +
	"|------|------|------|\n" +
	"| Test Lead | | |\n" +
	"| Safety Engineer | | |\n"

var contentSP005 = "# Threat Analysis and Risk Assessment (TARA)\n\n" +
	"## 1. Document Information\n\n" +
	"- **Project:** <!-- project name -->\n" +
	"- **Standard:** ISO 21434:2021 Chapter 9\n" +
	"- **Revision:** 1.0\n" +
	"- **Date:** <!-- YYYY-MM-DD -->\n\n" +
	"Note: Run fusaops tara to generate a structured TARA report automatically.\n\n" +
	"## 2. Asset Identification\n\n" +
	"| Asset | Category | Cybersecurity Properties |\n" +
	"|-------|----------|---------------------------|\n" +
	"| <!-- asset --> | <!-- HW/SW/Data/Function --> | <!-- C/I/A/Au --> |\n\n" +
	"## 3. Threat Scenarios\n\n" +
	"| ID | Asset | Threat Property | Description | Damage Scenario |\n" +
	"|----|-------|-----------------|-------------|------------------|\n" +
	"| TS-001 | <!-- asset --> | <!-- C/I/A/Au --> | <!-- threat --> | <!-- damage --> |\n\n" +
	"## 4. Risk Assessment\n\n" +
	"| Threat | Impact | Attack Feasibility | Risk Level | Treatment |\n" +
	"|--------|--------|-------------------|------------|----------|\n" +
	"| TS-001 | <!-- Critical/Major/Moderate/Negligible --> | <!-- High/Medium/Low/Very Low --> | <!-- Critical/High/Medium/Low --> | <!-- Mitigate/Transfer/Avoid/Accept --> |\n\n" +
	"## 5. Cybersecurity Goals\n\n" +
	"| ID | Goal | Risk Source | CAL |\n" +
	"|----|------|-------------|-----|\n" +
	"| CSG-001 | <!-- The system shall... --> | TS-001 | <!-- CAL 1-4 --> |\n\n" +
	"## 6. Controls and Countermeasures\n\n" +
	"| Threat | Control | Implementation Status |\n" +
	"|--------|---------|------------------------|\n" +
	"| TS-001 | <!-- control --> | <!-- planned/implemented --> |\n"

var contentSP006 = "# Software Configuration Index (SCI)\n\n" +
	"Note: Run fusaops sci to generate the SCI report automatically.\n\n" +
	"## 1. Document Information\n\n" +
	"- **Project:** <!-- project name -->\n" +
	"- **Standard:** DO-178C SS11.16\n" +
	"- **Software Level:** <!-- DAL-A through DAL-E -->\n" +
	"- **Revision:** 1.0\n" +
	"- **Date:** <!-- YYYY-MM-DD -->\n\n" +
	"## 2. Software Identification\n\n" +
	"| Item | Identifier | Version | Date |\n" +
	"|------|------------|---------|------|\n" +
	"| Software Product | <!-- name --> | <!-- version --> | <!-- date --> |\n\n" +
	"## 3. Tool Inventory\n\n" +
	"| Tool | Version | Qualification Status | Hash |\n" +
	"|------|---------|---------------------|------|\n" +
	"| FuSaOps | <!-- version --> | Tool Qualification Report attached | <!-- sha256 --> |\n\n" +
	"## 4. Artefact Inventory\n\n" +
	"| Artefact | Filename | Version/Hash | Location |\n" +
	"|----------|----------|--------------|---------|\n" +
	"| Requirements | .fusaops-trace.json | <!-- hash --> | Project root |\n" +
	"| Test Evidence | .fusaops-evidence.json | <!-- hash --> | Project root |\n" +
	"| SBOM | sbom.json | <!-- hash --> | Project root |\n\n" +
	"## 5. Configuration Control\n\n" +
	"All artefacts are under version control (Git). See fusaops audit-pack for the\n" +
	"integrity-verified evidence archive.\n"

var contentSP007 = "# Software Accomplishment Summary (SAS)\n\n" +
	"Note: Run fusaops sas to generate the SAS report automatically.\n\n" +
	"## 1. Document Information\n\n" +
	"- **Project:** <!-- project name -->\n" +
	"- **Standard:** DO-178C SS11.20\n" +
	"- **Software Level:** <!-- DAL-A through DAL-E -->\n" +
	"- **Revision:** 1.0\n" +
	"- **Date:** <!-- YYYY-MM-DD -->\n\n" +
	"## 2. System Overview\n\n" +
	"<!-- Brief description of the airborne system and the software's role -->\n\n" +
	"## 3. Software Life Cycle Summary\n\n" +
	"| Activity | Status | Evidence Reference |\n" +
	"|----------|--------|--------------------|\n" +
	"| Software Planning | Complete | Software Safety Plan |\n" +
	"| Requirements | Complete | Software Requirements Spec |\n" +
	"| Design | Complete | Software Design Description |\n" +
	"| Coding | Complete | Source code, code review records |\n" +
	"| Integration | Complete | Integration test report |\n" +
	"| Testing | Complete | .fusaops-evidence.json |\n" +
	"| Configuration Management | Complete | .fusaops-sci.json |\n" +
	"| Software Quality Assurance | Complete | .fusaops-qualify-report.json |\n" +
	"| Certification Liaison | Complete | This document |\n" +
	"| Problem Reporting | Complete | .fusaops-problems.json |\n\n" +
	"## 4. Deviations and Alternatives\n\n" +
	"<!-- List any deviations from the plan or alternative methods used -->\n\n" +
	"## 5. Outstanding Issues\n\n" +
	"<!-- List any open problem reports or known defects -->\n\n" +
	"## 6. Sign-off\n\n" +
	"| Role | Name | Date | Signature |\n" +
	"|------|------|------|----------|\n" +
	"| Project Designee (DER/DP) | | | |\n" +
	"| Software Project Lead | | | |\n"

var contentSP008 = "# Problem Report\n\n" +
	"Note: Run fusaops pr new to create a structured problem report automatically.\n\n" +
	"## Problem Report Information\n\n" +
	"- **PR ID:** PR-<!-- NNNN -->\n" +
	"- **Date Reported:** <!-- YYYY-MM-DD -->\n" +
	"- **Reported By:** <!-- name -->\n" +
	"- **Phase Detected:** <!-- requirements / design / coding / testing / field -->\n" +
	"- **Severity:** <!-- critical / major / minor / cosmetic -->\n" +
	"- **Status:** <!-- open / in-analysis / fix-in-progress / fixed / closed -->\n\n" +
	"## Problem Description\n\n" +
	"<!-- Describe the problem clearly and concisely. Include what was expected vs. observed. -->\n\n" +
	"## Reproduction Steps\n\n" +
	"1. <!-- step 1 -->\n" +
	"2. <!-- step 2 -->\n\n" +
	"## Root Cause Analysis\n\n" +
	"<!-- Describe the root cause once identified. -->\n\n" +
	"## Corrective Action\n\n" +
	"<!-- Describe the fix applied. Reference commit hash or change record. -->\n\n" +
	"## Verification\n\n" +
	"<!-- Describe how the fix was verified (test case added, review, etc.). -->\n\n" +
	"## Safety Impact Assessment\n\n" +
	"- **Safety relevant?** <!-- Yes / No -->\n" +
	"- **Standards affected:** <!-- ISO 26262 / DO-178C / IEC 61508 / ISO 21434 -->\n" +
	"- **Impact on FMEA/TARA:** <!-- describe any changes required -->\n\n" +
	"## Closure\n\n" +
	"- **Closed By:** <!-- name -->\n" +
	"- **Closed Date:** <!-- YYYY-MM-DD -->\n" +
	"- **Verification Reference:** <!-- test case ID or evidence file -->\n"

// standardTemplates is the built-in library of safety document templates.
var standardTemplates = []DocTemplate{
	{
		ID:       "SP-001",
		Name:     "Software Safety Plan",
		Kind:     DocKindPlan,
		Filename: "software-safety-plan.md",
		Content:  contentSP001,
	},
	{
		ID:        "SP-002",
		Name:      "Hazard Analysis and Risk Assessment (HARA)",
		Kind:      DocKindReport,
		Standards: []string{"ISO 26262", "IEC 61508"},
		Filename:  "hara.md",
		Content:   contentSP002,
	},
	{
		ID:       "SP-003",
		Name:     "Software Requirements Specification",
		Kind:     DocKindRequirements,
		Filename: "software-requirements-spec.md",
		Content:  contentSP003,
	},
	{
		ID:       "SP-004",
		Name:     "Test Plan and Verification Report",
		Kind:     DocKindPlan,
		Filename: "test-plan.md",
		Content:  contentSP004,
	},
	{
		ID:        "SP-005",
		Name:      "Threat Analysis and Risk Assessment (TARA)",
		Kind:      DocKindReport,
		Standards: []string{"ISO 21434"},
		Filename:  "tara-template.md",
		Content:   contentSP005,
	},
	{
		ID:        "SP-006",
		Name:      "Software Configuration Index",
		Kind:      DocKindReport,
		Standards: []string{"DO-178C"},
		Filename:  "sci-template.md",
		Content:   contentSP006,
	},
	{
		ID:        "SP-007",
		Name:      "Software Accomplishment Summary",
		Kind:      DocKindReport,
		Standards: []string{"DO-178C"},
		Filename:  "sas-template.md",
		Content:   contentSP007,
	},
	{
		ID:       "SP-008",
		Name:     "Problem Report Template",
		Kind:     DocKindChecklist,
		Filename: "problem-report-template.md",
		Content:  contentSP008,
	},
}

// applicableTemplates returns templates that apply to the requested standards.
// If standards is empty, all templates are returned.
func applicableTemplates(standards []string) []DocTemplate {
	if len(standards) == 0 {
		return standardTemplates
	}
	stdSet := make(map[string]bool, len(standards))
	for _, s := range standards {
		stdSet[strings.ToLower(s)] = true
	}
	var out []DocTemplate
	for _, t := range standardTemplates {
		if len(t.Standards) == 0 {
			out = append(out, t)
			continue
		}
		for _, ts := range t.Standards {
			if stdSet[strings.ToLower(ts)] {
				out = append(out, t)
				break
			}
		}
	}
	return out
}

// Generate writes safety documentation templates to outputDir under root.
// standards filters which templates to generate; empty means generate all.
//
//fusa:req REQ-FO-TMPL002
func Generate(root, outputDir string, standards []string) (*Report, error) {
	r := &Report{
		GeneratedAt: time.Now().UTC(),
		ProjectRoot: root,
		Tool:        "fusaops",
		ToolVersion: fusaops.Version,
		OutputDir:   outputDir,
		Standards:   standards,
	}
	if len(standards) == 0 {
		r.Standards = []string{"all"}
	}

	if err := os.MkdirAll(outputDir, 0o750); err != nil {
		return nil, fmt.Errorf("doctemplate: create output dir: %w", err)
	}

	templates := applicableTemplates(standards)
	for _, tmpl := range templates {
		path := filepath.Join(outputDir, tmpl.Filename)
		if err := os.WriteFile(path, []byte(tmpl.Content), 0o640); err != nil {
			return nil, fmt.Errorf("doctemplate: write %s: %w", path, err)
		}
		info, err := os.Stat(path)
		if err != nil {
			return nil, fmt.Errorf("doctemplate: stat %s: %w", path, err)
		}
		r.Generated = append(r.Generated, GeneratedDoc{
			TemplateID: tmpl.ID,
			Name:       tmpl.Name,
			Path:       path,
			Size:       info.Size(),
		})
		r.TotalGenerated++
	}

	r.Hash = computeHash(r)
	return r, nil
}

func computeHash(r *Report) string {
	tmp := *r
	tmp.Hash = ""
	data, err := json.Marshal(tmp)
	if err != nil {
		return ""
	}
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:])
}

// Save writes the report to path as indented JSON.
//
//fusa:req REQ-FO-TMPL003
func Save(path string, r *Report) error {
	data, err := json.MarshalIndent(r, "", "  ")
	if err != nil {
		return fmt.Errorf("doctemplate: marshal: %w", err)
	}
	if err := os.WriteFile(path, append(data, '\n'), 0o640); err != nil {
		return fmt.Errorf("doctemplate: write %s: %w", path, err)
	}
	return nil
}

// Load reads a persisted report from path.
//
//fusa:req REQ-FO-TMPL003
func Load(path string) (*Report, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fusaops.ErrNoConfig
		}
		return nil, fmt.Errorf("doctemplate: read %s: %w", path, err)
	}
	var r Report
	if err := json.Unmarshal(data, &r); err != nil {
		return nil, fmt.Errorf("doctemplate: unmarshal %s: %w", path, err)
	}
	return &r, nil
}

// Render writes a representation of the report to w.
// Supported formats: "text", "json".
//
//fusa:req REQ-FO-TMPL004
func Render(w io.Writer, r *Report, format string) error {
	switch format {
	case "text", "":
		return renderText(w, r)
	case "json":
		enc := json.NewEncoder(w)
		enc.SetIndent("", "  ")
		return enc.Encode(r)
	default:
		return fmt.Errorf("doctemplate: unsupported format %q", format)
	}
}

func renderText(w io.Writer, r *Report) error {
	fmt.Fprintf(w, "FuSaOps Safety Documentation Templates\n")
	fmt.Fprintf(w, "=======================================\n")
	fmt.Fprintf(w, "Project:   %s\n", r.ProjectRoot)
	fmt.Fprintf(w, "Tool:      %s v%s\n", r.Tool, r.ToolVersion)
	fmt.Fprintf(w, "Standards: %s\n", strings.Join(r.Standards, ", "))
	fmt.Fprintf(w, "Output:    %s\n", r.OutputDir)
	fmt.Fprintf(w, "Generated: %s\n", r.GeneratedAt.Format("2006-01-02T15:04:05Z"))
	fmt.Fprintf(w, "Templates: %d generated\n\n", r.TotalGenerated)

	for _, d := range r.Generated {
		fmt.Fprintf(w, "  [OK] %s — %s (%d bytes)\n", d.TemplateID, d.Name, d.Size)
		fmt.Fprintf(w, "       %s\n", d.Path)
	}
	if r.Hash != "" {
		fmt.Fprintf(w, "\nIntegrity: %s\n", r.Hash)
	}
	return nil
}
