// Package release provides build provenance and artifact manifest generation
// for FuSaOps multi-language safety releases.
//
// A FuSaOps release bundle consists of:
//   - sbom.json — the cross-language Software Bill of Materials (generated by the sbom package)
//   - provenance.json — the build environment and VCS state at release time
//   - artifact-manifest.json — SHA-256 hashes of all generated files
package release

import (
	"context"
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"os/exec"
	"runtime"
	"strings"
	"time"

	fusaops "github.com/SoundMatt/FuSaOps"
)

// File name constants for release artefacts.
//
//fusa:req REQ-FO-REL001
const (
	SBOMFile       = "sbom.json"
	ProvenanceFile = "provenance.json"
	ManifestFile   = "artifact-manifest.json"
)

// Provenance records the build environment at release time.
//
//fusa:req REQ-FO-REL001
type Provenance struct {
	GeneratedAt time.Time `json:"generatedAt"`
	Tool        string    `json:"tool"`
	ToolVersion string    `json:"toolVersion"`
	GoVersion   string    `json:"goVersion"`
	GOOS        string    `json:"goos"`
	GOARCH      string    `json:"goarch"`
	VCSRevision string    `json:"vcsRevision,omitempty"`
	VCSModified bool      `json:"vcsModified"`
	ProjectRoot string    `json:"projectRoot"`
}

// Artifact is a file path paired with its SHA-256 hex checksum.
//
//fusa:req REQ-FO-REL001
type Artifact struct {
	Path   string `json:"path"`
	SHA256 string `json:"sha256"`
	Size   int64  `json:"size"`
}

// Manifest is the list of released artefacts and their integrity hashes.
//
//fusa:req REQ-FO-REL001
type Manifest struct {
	GeneratedAt time.Time  `json:"generatedAt"`
	Artifacts   []Artifact `json:"artifacts"`
}

// BuildProvenance captures the current build environment and VCS state.
// VCS queries are best-effort: if git is unavailable, VCSRevision remains empty.
//
//fusa:req REQ-FO-REL002
func BuildProvenance(ctx context.Context, root string) (*Provenance, error) {
	p := &Provenance{
		GeneratedAt: time.Now().UTC(),
		Tool:        "fusaops",
		ToolVersion: fusaops.Version,
		GoVersion:   runtime.Version(),
		GOOS:        runtime.GOOS,
		GOARCH:      runtime.GOARCH,
		ProjectRoot: root,
	}

	// Best-effort git metadata.
	if rev, err := runGit(ctx, root, "rev-parse", "HEAD"); err == nil {
		p.VCSRevision = strings.TrimSpace(rev)
	}
	if status, err := runGit(ctx, root, "status", "--porcelain"); err == nil {
		p.VCSModified = strings.TrimSpace(status) != ""
	}

	return p, nil
}

// BuildManifest computes SHA-256 hashes for each file in paths.
//
//fusa:req REQ-FO-REL003
func BuildManifest(paths []string) (*Manifest, error) {
	m := &Manifest{
		GeneratedAt: time.Now().UTC(),
		Artifacts:   make([]Artifact, 0, len(paths)),
	}
	for _, p := range paths {
		a, err := hashFile(p)
		if err != nil {
			return nil, fmt.Errorf("release: hash %s: %w", p, err)
		}
		m.Artifacts = append(m.Artifacts, a)
	}
	return m, nil
}

// SaveJSON writes v to path as indented JSON.
//
//fusa:req REQ-FO-REL004
func SaveJSON(path string, v any) error {
	data, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return fmt.Errorf("release: marshal: %w", err)
	}
	if err := os.WriteFile(path, append(data, '\n'), 0o640); err != nil {
		return fmt.Errorf("release: write %s: %w", path, err)
	}
	return nil
}

// RenderProvenance writes provenance to w in the given format.
//
//fusa:req REQ-FO-REL004
func RenderProvenance(w io.Writer, p *Provenance, format string) error {
	switch format {
	case "text", "":
		fmt.Fprintf(w, "Tool:      %s %s\n", p.Tool, p.ToolVersion)
		fmt.Fprintf(w, "Go:        %s (%s/%s)\n", p.GoVersion, p.GOOS, p.GOARCH)
		fmt.Fprintf(w, "Generated: %s\n", p.GeneratedAt.Format("2006-01-02T15:04:05Z"))
		if p.VCSRevision != "" {
			modified := ""
			if p.VCSModified {
				modified = " (modified)"
			}
			fmt.Fprintf(w, "Commit:    %s%s\n", p.VCSRevision, modified)
		}
		return nil
	case "json":
		enc := json.NewEncoder(w)
		enc.SetIndent("", "  ")
		return enc.Encode(p)
	default:
		return fmt.Errorf("release: unsupported format %q", format)
	}
}

// RenderManifest writes the artifact manifest to w in the given format.
//
//fusa:req REQ-FO-REL004
func RenderManifest(w io.Writer, m *Manifest, format string) error {
	switch format {
	case "text", "":
		fmt.Fprintf(w, "Artifacts (%d):\n", len(m.Artifacts))
		for _, a := range m.Artifacts {
			fmt.Fprintf(w, "  %s  sha256:%s  (%d bytes)\n", a.Path, a.SHA256, a.Size)
		}
		return nil
	case "json":
		enc := json.NewEncoder(w)
		enc.SetIndent("", "  ")
		return enc.Encode(m)
	default:
		return fmt.Errorf("release: unsupported format %q", format)
	}
}

func hashFile(path string) (Artifact, error) {
	f, err := os.Open(path)
	if err != nil {
		return Artifact{}, err
	}
	defer func() { _ = f.Close() }()
	h := sha256.New()
	n, err := io.Copy(h, f)
	if err != nil {
		return Artifact{}, err
	}
	return Artifact{
		Path:   path,
		SHA256: fmt.Sprintf("%x", h.Sum(nil)),
		Size:   n,
	}, nil
}

func runGit(ctx context.Context, dir string, args ...string) (string, error) {
	cmd := exec.CommandContext(ctx, "git", args...)
	cmd.Dir = dir
	out, err := cmd.Output()
	if err != nil {
		return "", err
	}
	return string(out), nil
}
